version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dbname"]
      interval: 10s
      timeout: 5s
      retries: 5

  # app:
  #   build: .
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     POSTGRES_DSN: postgres://user:password@db:5432/dbname?sslmode=disable
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   command: ["go", "run", "cmd/api/main.go"]
  #   ports:
  #     - "8080:8080"

volumes:
  db_data:
